name: build sub-projects
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  build-frontend:
    name: build frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |-
          cd frontend/
          yarn install --check-files --frozen-lockfile
          yarn run build
          yarn run test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: Test results for frontend of web console
          report_paths: './frontend/test-reports/junit.xml'
          fail_on_failure: true
          require_tests: true
          detailed_summary: true
          job_name: build frontend
          update_check: true
          include_passed: true
  build-data-pipeline:
    name: build data pipeline
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
      - name: Build & Test data pipeline spark application
        run: |-
          cd ./src/data-pipeline/spark-etl
          gradle clean build
          gradle jacocoAggregatedReport
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          check_name: Test results for data pipeline spark application
          report_paths: './src/data-pipeline/spark-etl/build/test-results/test/TEST-*.xml'
          fail_on_failure: true
          require_tests: true
          detailed_summary: true
          job_name: build data pipeline
          update_check: true
          include_passed: true
      - name: Add coverage to PR
        id: jacoco
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
        uses: madrapps/jacoco-report@v1.4
        with:
          paths: ./src/data-pipeline/spark-etl/build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Data Pipeline spark application's test coverage
          min-coverage-overall: 80
          min-coverage-changed-files: 80
  build-data-pipeline-example:
    name: build data pipeline example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
      - name: Build & Test data pipeline examples
        run: |-
          cd ./examples/custom-plugins
          ./build.sh