name: build data pipeline
on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
      - name: Build & Test data pipeline spark application
        run: |-
          cd ./src/data-pipeline/spark-etl
          gradle clean build
          gradle jacocoAggregatedReport
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: './src/data-pipeline/spark-etl/build/test-results/test/TEST-*.xml'
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.4
        with:
          paths: ./src/data-pipeline/spark-etl/build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Data Pipeline spark application's test coverage
          min-coverage-overall: 80
          min-coverage-changed-files: 80
